name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: infra-container-scaleset
    container:
      image: ubuntu
      options: -u ubuntu
    steps:
      - run: uname -a
